---
title: "Notes for maternal output paper"
output: html_notebook
csl: "../references/cjfas.csl"
bibliography: "../references/maternal-output.bib"
---

# Reading list
Walker 2005
Monteleagre-Quijano (2014)
Blue sharks (2 papers)

### Huveneers et al [-@huveneers_reproductive_2007]
- 3 species of Wobbegong, ovarian follicle development supported a three year reproductive cycle. Females found concurrently sat three different stages of development. 

### Braccini et al [-@braccini_determining_2006]
- Piked spurdog
- Used both maternity ogives and pregnancy ogives
- Pregnancy ogives had $P_{Max}$ of 1 because there was around a two year gestation period
- Had to make some assumptions about follicle growth rates because of asynchronous reproduction, but interesting paper and good data

### Baremore and Passerotti [-@baremore_reproduction_2013]
- Limbatus
- Only pregnant females included...may need to check this
- Ogive multiplied by 0.5

### Baremore and Passerotti [-@baremore_reproduction_2012]
- Plumbeus
- Need to check with Ivy about the criteria used to determine maternal status, but seems to be pregnant females
- Possible 2 or 3 year reproductive cycle

### Taylor et al [-@taylor_living_2016]
- R. taylori
- Some individuals maturing at a large length caused the maternity ogive to be right-shifted for this species, highlighting importance even for annually reproducing species

### Harry et al [-@harry_age_2013]
- C. sorrah and C. tilstoni
- In C. sorrah maturity occurs at two but females don't begin reproducing to the following season / year. This is captured in the maternity ogive and is important given the species is relatively short-lived and fast maturing
- Some evidence of non-annual reproduction incorporated into the maternity ogive for C. tilstoni 

## Walker [-@walker_spatial_2007]
- Gummy shark

## Mejia-Falla et al 2012

### References
